name: EssentialsUltimate
main: nl.tacticaldev.essentials.Essentials
version: ${project.version}
authors: [TacticalDev]
api-version: 1.13
description: De EssentialsUltimate plugin
commands:
  test:
    description: "Test command"
  teleport:
    description: "Teleport to a player or a location"
    aliases:
      - tp
  teleportoffline:
    description: "Teleport to a player's offline location"
    aliases:
      - tpoffline
      - tpoffl
  setspawn:
    description: "Setspawn command"
    aliases:
      - spawnset
      - sspawn
  spawns:
    description: "List all the spawns"
    aliases:
      - spawnslist
      - listspawns
  spawn:
    description: "Teleport to a spawn"
    aliases:
      - telespawn
      - spawntele
      - spawnteleport
  deletespawn:
    description: "Delete a spawn"
    aliases:
      - delspawn
      - spawndelete
      - spawndele
  ban:
    description: "Ban a player"
    aliases:
      - eban
  tempban:
    description: "TemppBan a player"
    aliases:
      - etempban
      - tban
      - bantemp
      - ebantemp
      - etban
  ipban:
    description: "IPBan a player"
    aliases:
      - eipban
      - iban
      - eiban
  heal:
    description: "Heal a player"
    aliases:
      - eheal
  language:
    description: "Lang command"
    aliases:
      - lang
      - elang
      - elanguage
  setwarp:
    descripiton: "Set a warp"
    aliases:
      - createwarp
      - ecreatewarp
      - esetwarp
  warp:
    description: "Teleport to a warp"
    aliases:
      - teleportwarp
      - tpwarp
      - ewarp
      - etpwarp
  essentials:
    description: "Essentials command"
    aliases:
      - essentialsultimate
      - ess
      - essultimate
      - eultimate
  clear:
    description: "Clear a inventory of a player"
    aliases:
      - eclear
      - eclearinventory
      - clearinventory
      - clearinv
      - ci
      - eci
